on: [push]

name: Build

jobs:
  build_and_test:
    name: Turing Machine in Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
